image: node:alpine

variables:
  PUBLIC_URL: /

cache:
  paths:
    - node_modules

before_script:
  - npm ci

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  script:
    - npm run lint:gl
  artifacts:
    reports:
      codequality: gl-codequality.json

test:
  stage: test
  script:
    - npm run test:gl
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

pages:
  stage: deploy
  script:
    - npm run build
    - mv public _public
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
