image: node:alpine

variables:
  PUBLIC_URL: /

cache:
  untracked: true
  paths:
    - node_modules
  key: "$CI_BUILD_NAME"

before_script:
  - npm ci

stages:
  - lint-site
  - test-site
  - deploy-site
  - lint-resume
  - build-resume

lint-site:
  stage: lint-site
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
  script:
    - npm run lint:gl
  artifacts:
    reports:
      codequality: gl-codequality.json
  needs: []

test-site:
  stage: test-site
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
  script:
    - npm run test:gl
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  needs: []

pages:
  stage: deploy-site
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - npm run build
    - mv public _public
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  needs:
    - lint-site
    - test-site

lint-resume:
  stage: lint-resume
  image: torrentofshame/lualatex-texliveonfly
  script:
    - chktex simonweizman.tex
  needs: []

build-resume:
  stage: build-resume
  image: torrentofshame/lualatex-texliveonfly
  script:
    - texliveonfly --compiler=latexmk --arguments='-pdflua -interaction=nonstopmode' simonweizman.tex
  artifacts:
    paths:
      - ./*.pdf
  needs:
    - lint-resume
