image: node:alpine

variables:
  PUBLIC_URL: /

cache:
  paths:
    - node_modules

stages:
  - deploy

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build --production
    - mv public _public
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master