image: node:12.18.4

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build
  - yarn install
pages:
  stage: deploy
  script:
    - yarn build --production
    - cp public/index.html public/404.html
    - mv public _public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master