image: node:alpine

variables:
  PUBLIC_URL: /

cache:
  paths:
    - node_modules

before_script:
  - npm ci

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
  script:
    - npm run lint:gl
  artifacts:
    reports:
      codequality: gl-codequality.json
  needs: []

test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
  script:
    - npm run test:gl
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  needs: []

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - npm run build
    - mv public _public
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  needs:
    - lint
    - test
