image: node:12.18.4

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build
  - CI=false yarn install
  - CI=false yarn add react-bootstrap bootstrap

pages:
  stage: deploy
  script:
    - CI=false yarn build
    - rm -rf public
    - cp build/index.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master